before_install: 
- sudo apt-get update
- sudo apt-get install apache2.2-bin bison cdbs curl dpkg-dev elfutils devscripts fakeroot flex fonts-thai-tlwg g++ git-core git-svn gperf language-pack-da language-pack-fr language-pack-he language-pack-zh-hant libapache2-mod-php5 libasound2-dev libbrlapi-dev libav-tools libbz2-dev libcairo2-dev libcap-dev libcups2-dev libcurl4-gnutls-dev libdrm-dev libelf-dev libexif-dev libgconf2-dev libgl1-mesa-dev libglib2.0-dev libglu1-mesa-dev libgnome-keyring-dev libgtk2.0-dev libkrb5-dev libnspr4-dev libnss3-dev libpam0g-dev libpci-dev libpulse-dev libsctp-dev libspeechd-dev libsqlite3-dev libssl-dev libudev-dev libwww-perl libxslt1-dev libxss-dev libxt-dev libxtst-dev mesa-common-dev openbox patch perl php5-cgi pkg-config python python-cherrypy3 python-crypto python-dev python-numpy python-opencv python-openssl python-psutil rpm ruby subversion ttf-dejavu-core ttf-indic-fonts ttf-kochi-gothic ttf-kochi-mincho wdiff xfonts-mathml zip
- git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
- export PATH=$PATH:$(pwd)/depot_tools
- fetch --no-history webrtc
- ninja -C src/out/Release
language: cpp
compiler:
- gcc
script: 
- make WEBRTCROOT=.
